PMS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from products.views.langing_page import LandingPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('products/', include('products.urls', namespace="products")),
    path('user/', include('user.urls', namespace="user")),

]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path
from products.views.category_create import category_create_view
from products.views.product_action import product_action_view
from products.views.product_create import product_create_view
from products.views.product_delete import product_delete_view
from products.views.product_detail import product_detail_view
from products.views.product_list import product_list, stock_actions_list_view
from products.views.product_update import product_update_view
from products.views.stock_action import stock_action_view

app_name = 'products'

urlpatterns = [
    path('', product_list, name='product-list'),
    path('update/<int:pk>/', product_update_view, name='product-update'),
    path('product-action/<int:pk>/', product_action_view, name='product-action'),
    path('detail/<int:pk>/', product_detail_view, name='product-detail'),
    path('create/', product_create_view, name='product-create'),
    path('delete/<int:pk>/', product_delete_view, name='product-delete'),
    path('action/', stock_action_view, name='action-create'),
    path('action/list/', stock_actions_list_view, name='action-list'),
    path('category/create/', category_create_view, name='category-create'),
]

products/models/action_model.py
from django.db import models
from django.utils import timezone
from products.models.product_model import Product


class Actions(models.Model):
    ACTION_TYPE = [("giriş", "Giriş"), ("çıkış", "Çıkış")]

    action_type = models.CharField(verbose_name='Stok Hareketi', max_length=10, choices=ACTION_TYPE, null=False,
                                   blank=False)
    product_name = models.ForeignKey(Product, verbose_name="Ürün İsmi", on_delete=models.CASCADE, related_query_name='actions')
    action_quantity = models.PositiveIntegerField(verbose_name='İşlem Miktarı', blank=True, null=True, default=0)
    action_date = models.DateTimeField(verbose_name='Tarih-Saat', default=timezone.now)  # models.DateTimeField(default=timezone.now)
    customer = models.CharField(verbose_name='Müşteri', max_length=100, blank=True, null=True)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True, blank=True, default=1)
    quantity = models.OneToOneField(Product, on_delete=models.CASCADE, null=True, blank=True, related_name='action', verbose_name='Miktar')

    class Meta:
        verbose_name = "Stok Hareketi"
        verbose_name_plural = "Stok Hareketleri"
        ordering = ['-action_date']



    def __str__(self):
        return f"{self.product_name}-->{self.action_type}"

products/models/product_model.py
from django.db import models


class Product(models.Model):
    product_name = models.CharField(max_length=55, verbose_name='Ürün İsmi', unique=True)
    quantity = models.PositiveIntegerField(verbose_name='Ürün Miktarı')
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True, blank=True)
    content = models.TextField(verbose_name="Ürün Açıklaması", max_length=255, null=True, blank=True)


    class Meta:
        verbose_name = "Ürün"
        verbose_name_plural = "Ürünler"
        ordering = ("-id",)

    def __str__(self):
        return self.product_name


class Category(models.Model):
    name = models.CharField(max_length=30, unique=True, verbose_name='Kategori İsmi')

    class Meta:
        verbose_name = "Kategori"
        verbose_name_plural = "Kategoriler"
        ordering = ['-id']

    def __str__(self):
        return self.name

products/forms/action_create_form.py
from django import forms

from products.models.action_model import Actions


class ActionCreateForm(forms.ModelForm):
    class Meta:
        model = Actions
        fields = ['action_type', 'product_name', 'action_quantity', 'customer']

products/forms/category_create_form.py
from django import forms
from products.models.product_model import Category


class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

    # def clean_name(self):
    #     name = self.cleaned_data.get('name')
    #     if not name:
    #         raise forms.ValidationError('Yeni bir kategori ismi girmeniz gerekiyor')

products/forms/product_action_form.py
from django import forms
from products.models.action_model import Actions


class ProductActionForm(forms.ModelForm):
    class Meta:
        model = Actions
        fields = ['action_type', 'product_name', 'action_quantity', 'customer']

products/forms/product_create_form.py
from django import forms
from products.models.product_model import Product


class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_name', 'quantity', 'category', 'content']

products/forms/product_search_form.py
from django import forms
from products.models.product_model import Product


class ProductSearchForm(forms.ModelForm):
    # indir_excel_csv = forms.BooleanField(required=False)

    class Meta:
        model = Product
        fields = ['product_name']

products/forms/product_update_form.py
from django import forms
from products.models.product_model import Product


class ProductUpdateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_name', 'quantity', 'category', 'content']

products/views/category_create.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from products.forms.category_create_form import CategoryCreateForm


@login_required
def category_create_view(request):
    form = CategoryCreateForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request, 'BAŞARILI --> Yeni Ürün Kategorisi Oluşturuldu.')
        return redirect('products:product-list')
    context = {
        "form": form,
        "title": "Yeni Ürün Kategorisi Ekle",
    }
    return render(request, "products/product-create.html", context)

products/views/langing_page.py
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


class LandingPageView(LoginRequiredMixin, generic.TemplateView):
    template_name = "landing-page.html"
    login_url = 'user/login'

products/views/product_action.py
from django.contrib import messages
from django.shortcuts import render, redirect
from products.forms.product_action_form import ProductActionForm
from products.models.action_model import Actions
from products.models.product_model import Product
from django.contrib.auth.decorators import login_required


def product_action_view(request, pk):
    product = Product.objects.get(id=pk)
    form = ProductActionForm(instance=product)
    # TODO: Bu alan sadece ürüne yönelik işlem için ileride tekrar düzenlenecek
    context = {
        'form': form,
        'title': 'Stok Güncelle',
        'pk': pk
    }
    return render(request, 'products/product-action.html', context)

products/views/product_create.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from products.forms.product_create_form import ProductCreateForm


@login_required
def product_create_view(request):
    form = ProductCreateForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request, 'Stok ekleme başarılı.')
        return redirect('products:product-list')

    context = {
        "form": form,
        "title": "Ürün Ekle",
    }

    return render(request, "products/product-create.html", context)

# class ProductCreateView(CreateView):
#     template_name = "products/product-create.html"
#     form_class = ProductCreateForm

products/views/product_delete.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from products.models.product_model import Product


@login_required
def product_delete_view(request, pk):
    queryset = Product.objects.get(id=pk)

    if request.method == 'POST':
        queryset.delete()
        messages.success(request, 'BAŞARILI --> Ürün stoklardan silindi.')
        return redirect('products:product-list')
    return render(request, 'products/product-delete.html', {"queryset": queryset, 'title': 'Stok Sil'})

products/views/product_detail.py
from django.shortcuts import render
from products.models.product_model import Product
from django.contrib.auth.decorators import login_required


@login_required
def product_detail_view(request, pk):
    queryset = Product.objects.get(id=pk)
    title = "Ürün Detayı"

    context = {
        'title': title,
        'queryset': queryset,
    }

    return render(request, 'products/product-detail.html', context)

products/views/product_list.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render
from products.forms.product_search_form import ProductSearchForm
from products.models.action_model import Actions
from products.models.product_model import Product
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


@login_required
def product_list(request):
    queryset = Product.objects.all()
    form = ProductSearchForm(request.POST or None)
    if request.method == 'POST':
        query = form['product_name'].value()
        queryset = queryset.filter(Q(product_name__icontains=query) |
                                   Q(category__name__icontains=query)).distinct()

    paginator = Paginator(queryset, 25)  # Show 25 result per page.

    page = request.GET.get('page')

    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    context = {
        'title': 'Ürünlere ait stok listesi',
        'queryset': queryset,
        'form': form
    }

    return render(request, 'products/product-list.html', context)


@login_required
def stock_actions_list_view(request):

    queryset = Actions.objects.all()
    # form = ProductSearchForm(request.POST or None)
    # if request.method == 'POST':
    #     query = form['product_name'].value()
    #
    #     queryset = queryset.filter(Q(product_name__icontains=query) |
    #                                Q(category__icontains=query)).distinct()

    paginator = Paginator(queryset, 50)  # Show 25 result per page.

    page = request.GET.get('page')

    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    context = {
        'title': 'Stok Hareketleri Listesi',
        'queryset': queryset,
        #'form': form,
    }

    return render(request, 'products/action-list.html', context)

products/views/product_update.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from products.forms.product_update_form import ProductUpdateForm
from products.models.product_model import Product


@login_required
def product_update_view(request, pk):
    queryset = Product.objects.get(id=pk)
    form = ProductUpdateForm(instance=queryset)
    if request.method == 'POST':
        form = ProductUpdateForm(request.POST, instance=queryset)
        if form.is_valid():
            product_name = form.cleaned_data['product_name']
            quantity = form.cleaned_data['quantity']
            form.save()
            messages.success(request, f"BAŞARILI -->{product_name} Ürün {quantity} birim olarak güncellendi.")
            return redirect('products:product-list')

    context = {
        'form': form,
        'title': 'Stok Güncelle',
        'pk': pk
    }
    return render(request, 'products/product-update.html', context)

products/views/stock_action.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from products.forms.action_create_form import ActionCreateForm
from products.models.action_model import Actions
from products.models.product_model import Product

@login_required
def stock_action_view(request):
    # product = Product.objects.get(id=pk)
    # queryset = Actions.objects.filter(product_name_id=product.product_name__id)
    form = ActionCreateForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        product = Product.objects.get(product_name=instance.product_name)
        if instance.action_type == 'çıkış':
            if product.quantity >= instance.action_quantity:
                product.quantity -= instance.action_quantity
                messages.success(request,
                                 f"BAŞARILI --> Stok çıkışı yapıldı! {str(instance.action_quantity)} birim {str(instance.product_name)}")
                instance.save()
                product.save()
                return redirect('products:product-detail', product.id)

            else:
                messages.success(request, "BAŞARISIZ Stok çıkışı! --> Stok Miktarlarını dikkate alarak çıkış yapınız!!")
                return redirect('products:product-detail', product.id)

        if instance.action_type == 'giriş':
            product.quantity += instance.action_quantity
            instance.save()
            product.save()
            messages.success(request,f"BAŞARILI Stok girişi --> {str(instance.action_quantity)} birim {str(instance.product_name)}")
            return redirect('products:product-detail', product.id)

    context = {
        "title": 'Stok Hareketi',
        "form": form,
    }
    return render(request, "products/action-create.html", context)

templates/products/action-create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}{{ title }}{% endblock %}


<!-- İçerik -->
{% block content %}
<div class="container py-sm-3">
    <div class="p-5 mb-sm-4 bg-light rounded-3">
      <div class="container-fluid py-sm-2">
        <h1 class="display-5 fw-bold">{{ title }}</h1>
    {% load crispy_forms_tags %}
    <form method='POST' action=''>
        {% csrf_token %}
		{{form | crispy}}
        <br>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a href="{% url 'products:product-list' %}" class="btn btn-dark btn-lg" tabindex="-1" role="button">İptal</a>
        <input  class="btn btn-primary btn-lg" type="submit" value='Kaydet'/>
        </div>
    </form>
    </div>
    </div>
</div>

{% endblock %}

templates/products/action-list.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %} Stok Listesi {% endblock %}

{% block content %}
<main>
    <div class="container py-sm-3">
    <div class="p-5 mb-sm-4 bg-light rounded-3">
      <div class="container-fluid py-sm-1 align-self-center">
        <h1 class="display-5 fw-bold">Geçmiş Stok Hareketleri</h1>
        <a href="{% url 'products:product-list' %}" class="btn btn-primary btn-lg" type="button">Stok Listesi</a>
        <a href="{% url 'products:action-create' %}" class="btn btn-danger btn-lg" type="button">Yeni Stok Hareketi</a>
      </div>
       {% comment %} <div class="container-fluid row align-items-end col-auto">
        <form class="d-flex" method="post">
                    {% csrf_token %} {{form.as_table}}
                    <button class="btn btn-success btn-sm" type="submit">Ara</button>
                </form>
        </div>{% endcomment %}
    </div>

<table class="table table-striped table-hover table-sm">
    <thead class="table-dark">
        <tr>
          <th scope="col">S.NO</th>
          <th scope="col">STOK HAREKETİ</th>
          <th scope="col">KATEGORİ</th>
          <th scope="col">ÜRÜN İSMİ</th>
          <th scope="col">İŞLEM MİKTARI</th>
          <th scope="col">TARİH-SAAT</th>
        </tr>
    </thead>
    <tbody>
        {% for query in queryset %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td >{{ query.action_type | upper }}</td>
              <td >{{ query.category | title }}</td>
              <td>{{ query.product_name | capfirst }}</td>
              <td>{{ query.action_quantity | intcomma}}</td>
              <td>{{ query.action_date | timesince}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<div class="row">
<div class="col-md-6 col-md-offset-3">
<div class="pagination pagination-sm">
    <span class="step-links">
        {% if queryset.has_previous %}
            <a href="?page=1">&laquo; ilk</a>
            <a href="?page={{ queryset.previous_page_number }}">önceki sayfa</a>
        {% endif %}

        <span class="current page-item active">
            Sayfa {{ queryset.number }} / {{ queryset.paginator.num_pages }}.
        </span>

        {% if queryset.has_next %}
            <a href="?page={{ queryset.next_page_number }}">sonraki sayfa</a>
            <a href="?page={{ queryset.paginator.num_pages }}">son &raquo;</a>
        {% endif %}
    </span>
</div>
</div>
</div>
</div>


</main>
 {% endblock %}

templates/products/product-action.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}{{ title }}{% endblock %}


<!-- İçerik -->
{% block content %}
<div class="container py-sm-3">
    <div class="p-5 mb-sm-4 bg-light rounded-3">
      <div class="container-fluid py-sm-2">
        <h1 class="display-5 fw-bold">{{ title }}</h1>
    {% load crispy_forms_tags %}
    <form method='POST' action=''>
        {% csrf_token %}
		{{form | crispy}}
        <br>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a href="{% url 'products:product-detail' pk %}" class="btn btn-dark btn-lg" tabindex="-1" role="button">İptal</a>
        <input  class="btn btn-primary btn-lg" type="submit" value='Kaydet'/>
        </div>
    </form>
    </div>
    </div>
</div>

{% endblock %}

templates/products/product-create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}{{ title }}{% endblock %}


<!-- İçerik -->
{% block content %}
<div class="container py-sm-3">
    <div class="p-5 mb-sm-4 bg-light rounded-3">
      <div class="container-fluid py-sm-2">
        <h1 class="display-5 fw-bold">{{ title }}</h1>
    {% load crispy_forms_tags %}
    <form method='POST' action=''>
        {% csrf_token %}
		{{form | crispy}}
        <br>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a href="{% url 'products:product-list' %}" class="btn btn-dark btn-lg" tabindex="-1" role="button">İptal</a>
        <input  class="btn btn-primary btn-lg" type="submit" value='Kaydet'/>
        </div>
    </form>
    </div>
    </div>
</div>

{% endblock %}

templates/products/product-delete.html
{% extends 'base.html' %}
{% block title %} {{ title}} {% endblock %}

{% block content %}
<main>
    <div class="container py-sm-3">
    <div class="p-5 mb-sm-4 bg-light rounded-3">
      <div class="container-fluid py-sm-1">
        <h1 class="display-5 fw-bold">{{ title }}</h1>
             <form method="post" action="">
                {% csrf_token %}
                <h2>Bu <b>{{ queryset.product_name }}</b> ürünü silmek istediğinizden emin misiniz?</h2><br>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <button type="submit" class="btn btn-danger btn-lg" data-bs-dismiss="modal">Evet</button>
                <a href="{% url 'products:product-detail' queryset.id %}" type="button" class="btn btn-primary btn-lg">İptal</a>
            </div>
        </form>
      </div>

</main>
 {% endblock %}

templates/products/product-detail.html
{% extends 'base.html' %}
{% block title %} {{ title}} {% endblock %}

{% block content %}
<main>
    <div class="container py-sm-3">
    <div class="p-5 mb-sm-4 bg-light rounded-3">
      <div class="container-fluid py-sm-1">
        <h1 class="display-5 fw-bold">{{ title }}</h1>

        <a href="{% url 'products:product-list' %}" class="btn btn-primary btn-lg" type="button">Stok Listesi</a>
        <a href="{% url 'products:action-create' %}" class="btn btn-primary btn-lg" type="button">Stok Ekle/Çık</a>
      </div>
    </div>

<table class="table table-striped table-hover table-sm">
    <thead class="table-dark">
        <tr>
          <th scope="col">STOK_NO</th>
          <th scope="col">KATEGORİ</th>
          <th scope="col">ÜRÜN İSMİ</th>
          <th scope="col">STOK DURUMU</th>
          <th scope="col">AÇIKLAMALAR</th>
          <th scope="col">STOK SİL</th>

        </tr>
    </thead>
    <tbody>
        <tr>
          <th scope="row">{{ queryset.id }}</th>
          <td >{{ queryset.category }}</td>
          <td><a href="{% url 'products:product-update' queryset.id %}" class="btn btn-primary btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Ürün Güncelle">{{ queryset.product_name }}</a></td>
          <td>  {{ queryset.quantity}}</td>
          <td>{{ queryset.content }}</td>
          <td><a href="{% url 'products:product-delete' queryset.id %}" class="btn btn-danger btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Ürün Sil"><b>X</b></a></td>
        </tr>
    </tbody>
</table>

  </div>
</main>
 {% endblock %}

templates/products/product-list.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %} Stok Listesi {% endblock %}

{% block content %}
<main>
    <div class="container py-sm-3">
    <div class="p-5 mb-sm-4 bg-light rounded-3 row">
      <div class="container-fluid py-sm-1 col-md-8 align-self-center">
        <h2 class="display-5 fw-bold">Stok listesi</h2>
        <p class="col-md-8">Stoklarınıza buradan ekleme çıkarma yapabilir, stok listesinden isteğiniz ürünü güncelleyip, silebilir ve detay bilgilerini kontrol edebilirsiniz.</p>
        <a href="{% url 'landing-page' %}" class="btn btn-primary btn-lg" type="button">&laquo; Anasayfa</a>
        <a href="{% url 'products:action-create' %}" class="btn btn-danger btn-lg" type="button">Stok Girişi-Çıkışı Yap</a>

      </div>
        <div class="container-fluid row align-items-end col-auto">
        <form class="d-flex" method="post">
                    {% csrf_token %} {{form.as_table}}
                    <button class="btn btn-success btn-sm" type="submit">Ara</button>
                </form>
        </div>
    </div>

<table class="table table-striped table-hover table-sm">
    <thead class="table-dark">
        <tr>
          <th scope="col">S.NO</th>
          <th scope="col">KATEGORİ</th>
          <th scope="col" data-bs-toggle="tooltip" data-bs-placement="top" title="Ürün Detayı">ÜRÜN İSMİ</th>
          <th scope="col" data-bs-toggle="tooltip" data-bs-placement="top" title="Stok Güncelle">STOK DURUMU</th>
          <th scope="col" data-bs-toggle="tooltip" data-bs-placement="top" title="Ürün Sil">STOK SİL</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in queryset %}
            <tr>
              <th scope="row">{{ forloop.counter | ordinal }}</th>
              <td >{{ obj.category | capfirst }}</td>
              <td><a href="{% url 'products:product-detail' obj.id %}" data-bs-toggle="tooltip" data-bs-placement="top" title="Ürün Detayı">{{ obj.product_name | capfirst }}</a></td>
              <td><a href="{% url 'products:product-update' obj.id %}" class="btn btn-outline-success btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Stok Güncelle">{{ obj.quantity | intcomma}}</a></td>
              <td><a href="{% url 'products:product-delete' obj.id %}" class="btn btn-outline-danger btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Ürün Sil"><b>X</b></a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<div class="row">
<div class="col-md-6 col-md-offset-3">
<div class="pagination pagination-sm">
    <span class="step-links">
        {% if queryset.has_previous %}
            <a href="?page=1">&laquo; ilk sayfa</a>
            <a href="?page={{ queryset.previous_page_number }}">önceki</a>
        {% endif %}

        <span class="current page-item active">
            Sayfa {{ queryset.number }} / {{ queryset.paginator.num_pages }}.
        </span>

        {% if queryset.has_next %}
            <a href="?page={{ queryset.next_page_number }}">sonraki</a>
            <a href="?page={{ queryset.paginator.num_pages }}">son sayfa &raquo;</a>
        {% endif %}
    </span>
</div>
</div>
</div>
</div>

</main>
 {% endblock %}

templates/products/product-update.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}{{ title }}{% endblock %}


<!-- İçerik -->
{% block content %}
<div class="container py-sm-3">
    <div class="p-5 mb-sm-4 bg-light rounded-3">
      <div class="container-fluid py-sm-2">
        <h1 class="display-5 fw-bold">{{ title }}</h1>
    {% load crispy_forms_tags %}
    <form method='POST' action=''>
        {% csrf_token %}
		{{form | crispy}}
        <br>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a href="{% url 'products:product-detail' pk %}" class="btn btn-dark btn-lg" tabindex="-1" role="button">İptal</a>
        <input  class="btn btn-primary btn-lg" type="submit" value='Kaydet'/>
        </div>
    </form>
    </div>
    </div>
</div>

{% endblock %}