PMS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from products.views.langing_page import LandingPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('products/', include('products.urls', namespace="products")),
    path('user/', include('user.urls', namespace="user")),

]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path
from products.views.category_create import category_create_view
from products.views.product_action import product_action_view
from products.views.product_create import product_create_view
from products.views.product_delete import product_delete_view
from products.views.product_detail import product_detail_view
from products.views.product_list import product_list, stock_actions_list_view
from products.views.product_update import product_update_view
from products.views.stock_action import stock_action_view

app_name = 'products'

urlpatterns = [
    path('', product_list, name='product-list'),
    path('update/<int:pk>/', product_update_view, name='product-update'),
    path('product-action/<int:pk>/', product_action_view, name='product-action'),
    path('detail/<int:pk>/', product_detail_view, name='product-detail'),
    path('create/', product_create_view, name='product-create'),
    path('delete/<int:pk>/', product_delete_view, name='product-delete'),
    path('action/', stock_action_view, name='action-create'),
    path('action/list/', stock_actions_list_view, name='action-list'),
    path('category/create/', category_create_view, name='category-create'),
]

user/urls.py
from django.urls import path
from . import views
from .views import MyPasswordChangeView, MyPasswordResetDoneView

app_name = 'user'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('change-password/', MyPasswordChangeView.as_view(), name='password-change'),
    path('change-password/done', MyPasswordResetDoneView.as_view(), name='password-change-done'),

]

templates/base.html
{% load static %}
{% load humanize %}
<!doctype html>
<html lang="tr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="PMS v.1.5">
    <meta name="author" content="Resul ÇALIŞKAN">
    <meta name="generator" content="Giraffe Analytics Production 2021">
    <title>{% block title %} Stok Yönetim Sistemi {% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/jumbotron/">



    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/navbar-top-fixed.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


  </head>
  <body>
{% include 'navbar.html' %}
{% include 'messages.html' %}
{% block content %} {% endblock %}

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <footer class="pt-3  text-muted border-top">
        <div class="container ml-1">
        <button type="button" class="btn btn-dark float-sm-start mx-auto" data-bs-toggle="modal" data-bs-target="#myModal">
    &copy; Giraffe Analytics 2021 Production.- PMS v.1.5
        </button>
        <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
          <!-- Modal content-->
            <div class="modal-content">

                <div class="modal-header">
                    <h4 class="modal-title">Giraffe Analytics</h4>
                    <h4 class="modal-title">System Information</h4>
                </div>

                <div class="modal-body">
                    <div class="dev-info">
                      <p class=""><b>STOK YÖNETİM PROGRAMI 2021</b></p>
                      <p>VERSION: 1.5</p><br>

                      <p class="modal-header"><b>DEVELOPER:</b></p>
                      <p>R.CALISKAN - G.A. MEMBERS</p>
                      <p>+90536XXXXXXX </p>
                      <p class="align-content-center"><img src="{% static 'image/logo.png' %}" alt="Developer Logo"></p>
                    </div>
                </div>

                <div class="modal-footer">
                  <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                </div>

            </div>
      </div>
  </div>
        </div>

    </footer>


  </body>
</html>

templates/landing-page.html
{% extends 'base.html' %}
{% block title %} Stok Yönetimi {% endblock %}

{% block content %}
<main>
    <div class="container py-sm-3">
    <div class="p-5 mb-sm-4 bg-light rounded-3">
      <div class="container-fluid py-sm-2">
        <h1 class="display-5 fw-bold">Stok Yönetimi</h1>
        <p class="col-md-8 fs-4">Stoklarınızın kontrolü sizde olsun..</p>
        <a href="{% url 'products:product-list' %}" class="btn btn-primary btn-lg" type="button">Stok İşlemleri</a>
                  <a href="{% url 'products:action-create' %}" class="btn btn-danger btn-lg" type="button">Stok Hareketi</a>
      </div>
    </div>

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Yeni Ürün Ekle</h2>
          <p>Stoklarınıza ürün kaydını buradan yapabilirsiniz... </p>
          <a href="{% url 'products:product-create' %}" class="btn btn-outline-light" type="button">Ürün Ekle</a>
          <a href="{% url 'products:category-create' %}" class="btn btn-outline-light" type="button">Kategori Ekle</a>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Stok Geçmişi</h2>
          <p>Geçmiş stok hareketlerine buradan bakabilirsiniz...</p>
          <a href="{% url 'products:action-list' %}" class="btn btn-outline-light" type="button">Stok Hareketleri</a>
        </div>
      </div>
    </div>
    </div>
</main>
 {% endblock %}

templates/messages.html
<style>
    .success{
     list-style: none;
     background-color: #1b1b44;
     color: white;
     box-shadow: 4px 4px 4px #e61c66;
     text-align: center;
 }
</style>
<div class="container w-100">
{% if messages %}
    <ul class="messages w-100">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
      </ul>
{% endif %}
</div>

templates/navbar.html
{% load crispy_forms_filters %}

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'landing-page' %}">Stok Yönetimi</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'products:product-list' %}">Stokları Gör</a>
        </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Stok İşlemleri
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'products:product-list' %}">Stok Listele</a></li>
              <li><a class="dropdown-item" href="{% url 'products:action-create' %}">Stok Girişi-Çıkışı</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'products:action-list' %}">Stok Hareketleri</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'products:product-create' %}">Ürün Ekle</a></li>
              <li><a class="dropdown-item" href="{% url 'products:category-create' %}">Kategori Ekle</a></li>
          </ul>
        </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Kullanıcı İşlemleri
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'user:register' %}">Yeni Kullanıcı Ekle</a></li>
              <li><a class="dropdown-item" href="{% url 'user:password-change' %}">Parola Değiştir</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'user:login' %}">Giriş Yap</a></li>
            <li><a class="dropdown-item" href="{% url 'user:logout' %}">Çıkış Yap</a></li>
          </ul>
        </li>
      </ul>



        {% if user.is_authenticated %}
        <a href="{% url 'user:logout' %}" class="btn btn-outline-danger" type="button">{{ user }} | Çıkış</a>
        {% else %}
        <a href="{% url 'user:login' %}" class="btn btn-outline-success" type="button">Giriş</a>
        {% endif %}

    </div>
  </div>
</nav>